server:
  port: 9002
  address: 0.0.0.0

spring:
  application:
    name: history
  jackson:
    serialization:
      # needed for serializing objects of type object
      FAIL_ON_EMPTY_BEANS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs #Keycloak Endpoint
  data:
    mongodb:
      database: ${HISTORY_DATABASE}
      host: ${HISTORY_HOST}
      port: ${HISTORY_PORT}
      username: ${HISTORY_USERNAME}
      password: ${HISTORY_PASSWORD}

history:
  save-interval: 72
  delete-interval: 0 0 * * * *

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
